name: Build

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              if: startsWith(github.ref, 'refs/tags/')
              uses: actions/checkout@v3

            - name: Make .env
              run: |
                  echo "REACT_APP_AWS_IDENTITYPOOLLD=$REACT_APP_AWS_IDENTITYPOOLLD">> .env
                  echo "REACT_APP_AWS_S3_BUCKET=$REACT_APP_AWS_S3_BUCKET">> .env
                  echo "REACT_APP_AWS_S3_REGION=$REACT_APP_AWS_S3_REGION">> .env
              env:
                  REACT_APP_AWS_IDENTITYPOOLLD: ${{ secrets.REACT_APP_AWS_IDENTITYPOOLLD }}
                  REACT_APP_AWS_S3_BUCKET: ${{ secrets.REACT_APP_AWS_S3_BUCKET }}
                  REACT_APP_AWS_S3_REGION: ${{ secrets.REACT_APP_AWS_S3_REGION }}

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 20.x

            - name: Setup Pnpm
              uses: pnpm/action-setup@v3

            - name: Get pnpm store directory
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

            - uses: actions/cache@v4
              name: Setup pnpm cache
              with:
                  path: ${{ env.STORE_PATH }}
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-

            - name: Dependencies Install & build
              run: |
                  pnpm i
                  pnpm build

            - name: Deploy Docs
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.ACTIONS_TOKEN  }}
                  publish_branch: "release-page"
                  publish_dir: ./build
